project_name: ipx
builds:
  - main: .
    binary: ipx
    dir: ./cmd/ipx
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows


archives:
    - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ .Arm }}"
      format: tar.gz
      format_overrides:
        - goos: indows
          format: zip
      replacements:
          darwin: MacOS
          linux: Linux
          windows: Windows
          386: i386
          
      wrap_in_directory: true
checksum:
  name_template: "checksums.txt"
release:
  draft: true  
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'